id: I129C947E
ocr_import_info:
  bdrc_scan_id: W24824
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-09-12 14:12:13.639520
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24824
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessFairUse
  reproduction_of: http://purl.bdrc.io/resource/MW24824
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དུངས་ཞེན་དཀར་པོ།
  languages:
  - bo
  author: དབལ་ཤུལ་རང་བྱུང་།
bases:
  I1KG22748:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22748
      total_pages: 166
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG22748.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
